apiVersion: v1
kind: Service
metadata:
  name: my-grpc-service
  labels:
    app: grpc-app
spec:
  selector:
    app: grpc-app
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP